### ISSUE TITLE
希望能配置一个timeout参数, 传递到 node_modules/ali-oss/lib/client.js 

### ISSUE THREAD

**Issue by xiaohuilam** [cipchk/ng-deploy-oss#11]
希望能配置一个timeout参数, 传递到 node_modules/ali-oss/lib/client.js 
```javascript
proto.request = async function request(params) {
  params.timeout = 1000000; // 配置的timeout参数
  const reqParams = createRequest.call(this, params);
  let result;
  let reqErr;
  ...
}
```

否则dist/整体较大会有超时的报错

**Comment by cipchk** [comment]
默认 [10秒](https://github.com/cipchk/ng-deploy-oss/blob/master/src/schematics/ali-oss/deploy.ts#L15) 不够吗？

的确是这里的 `timeout` 是指所有实例，我会调整更大一点。
