### ISSUE TITLE
可以将 index.html 的上传排到其他文件传完之后吗？

### ISSUE THREAD

**Issue by xiaohuilam** [cipchk/ng-deploy-oss#13]
您的插件真心好用，于是我司用他来结合 github actions 实现自动打包部署。但因为 github actions 在美国，上传到 OSS 贼慢所以发现一个问题：

这插件会在中途就上传 `index.html`， 而此时 `main-*.js` 、 `es6-*.js` 等主要JS代码还未上传完成，经过我们测试美国 Github Actions 服务器上传到境内沪杭 OSS 区域此过程大约需要90秒钟（我们目前10几个页面，可能业务也比较复杂），

在此90秒内，`index.html` 尝试去引用打包后新的 `main-*.js` 、 `es6-*.js`， 而后者（们）并未上传完成。

所以就会报出  `main-*.js` 、 `es6-*.js` 等 JS 的404错误。

希望此插件能优化下排序，保证JS传完后再传 `index.html`，万事俱备（js传完后），再处理东风（index.html）

![image](https://user-images.githubusercontent.com/6964962/109610550-df1d0100-7b67-11eb-8b76-8626e0e77ec8.png)

谢谢您了！

**Comment by cipchk** [comment]
fixed by `10.1.0`

**Comment by xiaohuilam** [comment]
修复的很快！谢谢大佬！刊误不是 `10.1.0` 而是 `10.0.3`

![image](https://user-images.githubusercontent.com/6964962/109630098-7c376400-7b7f-11eb-89a4-f51bc8edade1.png)
