### ISSUE TITLE
请问如何避免 DELETE 文件呢?

### ISSUE THREAD

**Issue by xiaohuilam** [cipchk/ng-deploy-oss#7]
因为删除会影响不刷新的用户, 他点击到其他页面, 组件JS 就 404 了.
希望提供一个选项, 避免 DELETE.

**Comment by cipchk** [comment]
@xiaohuilam 你是指 `Start checking pre-deleted files` 这一步骤吗？

**Comment by xiaohuilam** [comment]
> @xiaohuilam 你是指 `Start checking pre-deleted files` 这一步骤吗？

对的, 对的

**Comment by xiaohuilam** [comment]
类似于 rsync 的单向同步啦(只增不删)

**Comment by cipchk** [comment]
我能增加一个判断，但是我不确定对应的云存储支持覆盖（但应该是可以的）。

**Comment by xiaohuilam** [comment]
> 我能增加一个判断，但是我不确定对应的云存储支持覆盖（但应该是可以的）。

根据使用 OSS 的经验, putObject 是支持覆盖已存在object的

**Comment by cipchk** [comment]
@xiaohuilam 尝试使用 `9.0.0` 版本，只需要在 `angular.json` 增加 `deploy.options`：

```json
"preClean": true
```
